---

language: python
python:
  - 3.6
services: docker

env:
  global:
    - ROLE_NAME: nvidia-cuda
  matrix:
    - MOLECULE_DISTRO: ubuntu1804

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  - molecule test

notifications:
