---

# installation guide: https://nvidia.github.io/nvidia-container-runtime/

- name: container runtime | add repo key
  become: true
  apt_key:
    url: https://nvidia.github.io/nvidia-container-runtime/gpgkey
    state: present
  tags: install

- name: container runtime | add repo
  become: true
  apt_repository:
    repo: "{{ item }}"
    filename: nvidia-container-runtime
    state: present
  loop: "{{ lookup('url', 'https://nvidia.github.io/nvidia-container-runtime/{{ ansible_distribution | lower }}{{ ansible_distribution_version }}/nvidia-container-runtime.list', wantlist=True) | reject('match', '^[#]') | list }}"   # noqa 204
  tags: install

- name: container runtime | establish package
  become: true
  apt:
    name: nvidia-container-runtime
    state: present
  tags: install
