---

- name: cuda | pre-install tasks
  include_tasks: "{{ item }}"
  loop: "{{ query('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "pre_install_{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "pre_install_{{ ansible_distribution }}.yml"
        - "pre_install_{{ ansible_os_family }}.yml"
        - "pre_install_{{ ansible_system }}.yml"
      paths:
        - '{{ role_path }}/tasks/platform/'
  tags: install

- name: cuda | establish package
  when: nvidia_cuda_install_cuda
  package:
    name: cuda
    state: present
  tags: install
