---

- name: platform dependent vars
  include_vars: "{{ item }}"
  loop: "{{ query('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
      paths:
        - '{{ role_path }}/vars/platform'
  tags: always

- name: establish pre-requisites
  when: "ansible_distribution == 'Ubuntu'"
  become: true
  package:
    name: gpg-agent
    state: present

- name: establish nvidia driver
  when: not nvidia_cuda_install_cuda
  include_tasks: nvidia_driver.yml

- name: establish nvidia cuda
  when: nvidia_cuda_install_cuda
  include_tasks: cuda.yml

- name: establish nvidia container runtime
  when: nvidia_cuda_install_container_runtime
  include_tasks: container_runtime.yml

- name: add optimus support
  when: nvidia_cuda_add_optimus_support
  package:
    name: bumblebee-nvidia
    state: present
  tags: install
