---

- name: nvidia graphics card repo
  when: ansible_pkg_mgr == 'apt'
  become: true
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: present
    filename: nvidia-graphics
  tags: install

- name: establish nvidia driver
  when: not nvidia_cuda_install_cuda
  become: true
  package:
    name: nvidia-driver-{{ nvidia_cuda_driver_version }}
    state: present
  tags: install
